### ISSUE TITLE
NI USB-6259 BNC connection issue

### ISSUE THREAD

**Issue by ewan-mcghee** [slightlynybbled/daqmx#1]
Hi,

Found your daqmx package which looks super simple to use and just the thing I need, but encountered the following issue when trying to set a digital output to 1:

runfile('D:/LSD/Scripts/daqmx digital output control test.py', wdir='D:/LSD/Scripts')
Traceback (most recent call last):

  File "D:\LSD\Scripts\daqmx digital output control test.py", line 20, in <module>
    daq = NIDAQmxInstrument(serial_number='013DB9D6')

  File "C:\ProgramData\Anaconda3\lib\site-packages\daqmx\daqmx.py", line 496, in __init__
    for p in searcher.list_do_lines(device):

  File "C:\ProgramData\Anaconda3\lib\site-packages\daqmx\daqmx.py", line 791, in list_do_lines
    PyDAQmx.DAQmxGetDevDOLines(ctypes.addressof(dev_char_buffer), char_buffer, self.STRING_BUF_LEN)

  File "<string>", line 2, in function

  File "C:\ProgramData\Anaconda3\lib\site-packages\PyDAQmx\DAQmxFunctions.py", line 85, in mafunction
    return default_f(*args)

  File "C:\ProgramData\Anaconda3\lib\site-packages\PyDAQmx\DAQmxFunctions.py", line 62, in mafunction
    raise exception_class(errBuff.value.decode("utf-8"), f.__name__)

BufferTooSmallForStringError: Buffer is too small to fit the string.
Required Buffer Size in Bytes: 885
Buffer Length: 500

Status Code: -200228
 in function DAQmxGetDevDOLines

----

Using the NI-MAX package I can address the correct port and line and send out a +5V signal so the drivers etc are working and I hace identified the correct port and line.

If there is anything I can help woth / provide more information / test etc please let me know.

Cheers,

Ewan

**Comment by slightlynybbled** [comment]
Ewan -

Thank you for checking out daqmx!

I originally wrote this b/c I really disliked all other options out there,
but I only had one piece of hardware available to me at the time.  I was
hopeful that one or more contributors would like the package and contribute
hardware, but that hasn't happened.  Your problem appears to be simple
enough to fix, but I'm not confident that you won't have other issues and I
don't have your hardware to test on.  I'll upload a version with a longer
buffer size momentarily.  Good luck!

j

**Comment by slightlynybbled** [comment]
Uploaded v0.4.4, which directly addresses your error, but may have other issues.

Would love to have a pull request!

**Comment by ewan-mcghee** [comment]
Hi Jason,

Thats really amazing thanks - will be able to check it out later on today.

Do I just do an update via pip?

Also, apologies for asking, but what does a pull request actually mean? I've seen it lots of times on Github projects but I've never known what it means.

Will get back to you after I've given the update a try.

Cheers,

Ewan
________________________________

**Comment by slightlynybbled** [comment]
Yes, update via pip: `python -m pip install --upgrade daqmx`

A pull request is a process through which you can contribute to someone else's repository and help maintain the code.  In this case, it is particularly critical since I don't have the hardware in front of me.

In general, a pull request means that you will fork the repository to your user (top right in github), make your changes, then create a pull request.  This is literally a request for someone else to pull your code changes back into the primary repository.  Generally, this creates a review step and sometimes other changes are requested.  Of course, there are more details to attend to when you actually get into it, but this is a decent high-level overview.

good luck,

j

**Comment by ewan-mcghee** [comment]
Hi Jason,

Just wanted to say that the change you made worked perfectly and I am able to control the digital output via Python.

I will put in the pull request later on today. Just let me know if there is anything else you would like me to test.

Cheers,

Ewan

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by slightlynybbled** [comment]
Really great, glad it is working for you!

**Comment by ewan-mcghee** [comment]
Hi Jason,

Sorry to bother you again, but I am struggling to create the pull request on Github. I try use the new pull request function, but there is just the master branch and so I can't progress any further.

Thanks again for the adapter, it really makes things easier.

Cheers,

Ewan
________________________________

**Comment by slightlynybbled** [comment]
Is no trouble.  Glad to assist.

For this change, there is no pull request necessary.  I'm not sure what code you wish me to pull.  If all is working, then all is well!
